<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>AsyncVerifierTest.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">threadly$All_in_threadly_test.exec</a> &gt; <a href="index.source.html" class="el_package">org.threadly.test.concurrent</a> &gt; <span class="el_source">AsyncVerifierTest.java</span></div><h1>AsyncVerifierTest.java</h1><pre class="source lang-java linenums">package org.threadly.test.concurrent;

import static org.junit.Assert.*;

import java.util.concurrent.TimeoutException;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.threadly.ThreadlyTester;
import org.threadly.util.ExceptionUtils;
import org.threadly.util.StringUtils;

@SuppressWarnings(&quot;javadoc&quot;)
<span class="fc" id="L17">public class AsyncVerifierTest extends ThreadlyTester {</span>
  @BeforeClass
  public static void setupClass() {
<span class="fc" id="L20">    setIgnoreExceptionHandler();</span>
<span class="fc" id="L21">  }</span>
  
  @AfterClass
  public static void cleanupClass() {
<span class="fc" id="L25">    Thread.setDefaultUncaughtExceptionHandler(null);</span>
<span class="fc" id="L26">  }</span>
  
  private static final int ASYNC_WAIT_AMOUNT = 2;
  
  private AsyncVerifier verifier;
  
  @Before
  public void setup() {
<span class="fc" id="L34">    verifier = new AsyncVerifier();</span>
<span class="fc" id="L35">  }</span>
  
  @After
  public void cleanup() {
<span class="fc" id="L39">    verifier = null;</span>
<span class="fc" id="L40">  }</span>
  
  @Test (expected = TimeoutException.class)
  public void waitForTestTimeout() throws InterruptedException, TimeoutException {
<span class="nc" id="L44">    verifier.waitForTest(1);</span>
<span class="nc" id="L45">  }</span>
  
  @Test
  public void signalCompleteBeforeWaitTest() throws InterruptedException, TimeoutException {
<span class="fc" id="L49">    verifier.signalComplete();</span>
    
<span class="fc" id="L51">    verifier.waitForTest(1);  // no exception should throw as no blocking is needed</span>
<span class="fc" id="L52">  }</span>
  
  @Test
  public void signalCompleteAnotherThreadTest() {
<span class="fc" id="L56">    TestRunnable waitRunnable = new TestRunnable() {</span>
      @Override
      public void handleRunFinish() {
        try {
<span class="fc" id="L60">          verifier.waitForTest();</span>
<span class="nc" id="L61">        } catch (Exception e) {</span>
<span class="nc" id="L62">          throw ExceptionUtils.makeRuntime(e);</span>
<span class="fc" id="L63">        }</span>
<span class="fc" id="L64">      }</span>
    };
<span class="fc" id="L66">    new Thread(waitRunnable).start();</span>
    
    // should unblock thread
<span class="fc" id="L69">    verifier.signalComplete();</span>
    
<span class="fc" id="L71">    waitRunnable.blockTillFinished(); // should return quickly</span>
<span class="fc" id="L72">  }</span>
  
  @Test
  public void assertTrueTest() {
<span class="fc" id="L76">    verifier.assertTrue(true);</span>
<span class="fc" id="L77">  }</span>
  
  @Test (expected = RuntimeException.class)
  public void assertTrueFail() {
<span class="nc" id="L81">    verifier.assertTrue(false);</span>
<span class="nc" id="L82">  }</span>
  
  @Test
  public void assertFalseTest() {
<span class="fc" id="L86">    verifier.assertFalse(false);</span>
<span class="fc" id="L87">  }</span>
  
  @Test (expected = RuntimeException.class)
  public void assertFalseFail() {
<span class="nc" id="L91">    verifier.assertFalse(true);</span>
<span class="nc" id="L92">  }</span>
  
  @Test
  public void assertNullTest() {
<span class="fc" id="L96">    verifier.assertNull(null);</span>
<span class="fc" id="L97">  }</span>
  
  @Test (expected = RuntimeException.class)
  public void assertNullFail() {
<span class="nc" id="L101">    verifier.assertNull(new Object());</span>
<span class="nc" id="L102">  }</span>
  
  @Test
  public void assertNotNullTest() {
<span class="fc" id="L106">    verifier.assertNotNull(new Object());</span>
<span class="fc" id="L107">  }</span>
  
  @Test (expected = RuntimeException.class)
  public void assertNotNullFail() {
<span class="nc" id="L111">    verifier.assertNotNull(null);</span>
<span class="nc" id="L112">  }</span>
  
  @Test
  public void assertEqualsTest() {
<span class="fc" id="L116">    Object o = new Object();</span>
<span class="fc" id="L117">    verifier.assertEquals(o, o);</span>
<span class="fc" id="L118">    verifier.assertEquals(null, null);</span>
<span class="fc" id="L119">    verifier.assertEquals(1, 1);</span>
<span class="fc" id="L120">    verifier.assertEquals(1L, 1L);</span>
<span class="fc" id="L121">    verifier.assertEquals(1.1, 1.1);</span>
<span class="fc" id="L122">  }</span>
  
  @Test (expected = RuntimeException.class)
  public void assertEqualsObjectFail() {
<span class="nc" id="L126">    verifier.assertEquals(null, new Object());</span>
<span class="nc" id="L127">  }</span>
  
  @Test (expected = RuntimeException.class)
  public void assertEqualsNumberFail() {
<span class="nc" id="L131">    verifier.assertEquals(1, 10.0);</span>
<span class="nc" id="L132">  }</span>
  
  @Test (expected = RuntimeException.class)
  public void failTest() {
<span class="nc" id="L136">    verifier.fail();</span>
<span class="nc" id="L137">  }</span>
  
  @Test
  public void failMsgTest() {
<span class="fc" id="L141">    String msg = StringUtils.makeRandomString(5);</span>
    try {
<span class="nc" id="L143">      verifier.fail(msg);</span>
<span class="nc" id="L144">      fail(&quot;Exception should have thrown&quot;);</span>
<span class="fc" id="L145">    } catch (RuntimeException e) {</span>
<span class="fc" id="L146">      assertEquals(msg, e.getMessage());</span>
<span class="nc" id="L147">    }</span>
<span class="fc" id="L148">  }</span>
  
  @Test
  public void failThrowableTest() {
<span class="fc" id="L152">    Exception failure = new Exception();</span>
    try {
<span class="nc" id="L154">      verifier.fail(failure);</span>
<span class="nc" id="L155">      fail(&quot;Exception should have thrown&quot;);</span>
<span class="fc" id="L156">    } catch (RuntimeException e) {</span>
<span class="pc bpc" id="L157" title="1 of 2 branches missed.">      assertTrue(failure == e.getCause());</span>
<span class="nc" id="L158">    }</span>
<span class="fc" id="L159">  }</span>
  
  @Test (expected = RuntimeException.class)
  public void assertTrueFailAnotherThreadTest() throws InterruptedException, TimeoutException {
<span class="fc" id="L163">    new Thread(new Runnable() {</span>
      @Override
      public void run() {
        try {
<span class="nc" id="L167">          Thread.sleep(ASYNC_WAIT_AMOUNT);</span>
<span class="nc" id="L168">        } catch (InterruptedException e) {</span>
          // let thread exit
<span class="nc" id="L170">          return;</span>
<span class="nc" id="L171">        }</span>
        
<span class="nc" id="L173">        verifier.assertTrue(false);</span>
<span class="nc" id="L174">      }</span>
<span class="fc" id="L175">    }).start();</span>
    
<span class="nc" id="L177">    verifier.waitForTest();</span>
<span class="nc" id="L178">  }</span>
  
  @Test (expected = RuntimeException.class)
  public void assertFalseFailAnotherThreadTest() throws InterruptedException, TimeoutException {
<span class="fc" id="L182">    new Thread(new Runnable() {</span>
      @Override
      public void run() {
        try {
<span class="nc" id="L186">          Thread.sleep(ASYNC_WAIT_AMOUNT);</span>
<span class="nc" id="L187">        } catch (InterruptedException e) {</span>
          // let thread exit
<span class="nc" id="L189">          return;</span>
<span class="nc" id="L190">        }</span>
        
<span class="nc" id="L192">        verifier.assertFalse(true);</span>
<span class="nc" id="L193">      }</span>
<span class="fc" id="L194">    }).start();</span>
    
<span class="nc" id="L196">    verifier.waitForTest();</span>
<span class="nc" id="L197">  }</span>
  
  @Test (expected = RuntimeException.class)
  public void assertNullFailAnotherThreadTest() throws InterruptedException, TimeoutException {
<span class="fc" id="L201">    new Thread(new Runnable() {</span>
      @Override
      public void run() {
        try {
<span class="nc" id="L205">          Thread.sleep(ASYNC_WAIT_AMOUNT);</span>
<span class="nc" id="L206">        } catch (InterruptedException e) {</span>
          // let thread exit
<span class="nc" id="L208">          return;</span>
<span class="nc" id="L209">        }</span>
        
<span class="nc" id="L211">        verifier.assertNull(new Object());</span>
<span class="nc" id="L212">      }</span>
<span class="fc" id="L213">    }).start();</span>
    
<span class="nc" id="L215">    verifier.waitForTest();</span>
<span class="nc" id="L216">  }</span>
  
  @Test (expected = RuntimeException.class)
  public void assertNotNullFailAnotherThreadTest() throws InterruptedException, TimeoutException {
<span class="fc" id="L220">    new Thread(new Runnable() {</span>
      @Override
      public void run() {
        try {
<span class="nc" id="L224">          Thread.sleep(ASYNC_WAIT_AMOUNT);</span>
<span class="nc" id="L225">        } catch (InterruptedException e) {</span>
          // let thread exit
<span class="nc" id="L227">          return;</span>
<span class="nc" id="L228">        }</span>
        
<span class="nc" id="L230">        verifier.assertNotNull(null);</span>
<span class="nc" id="L231">      }</span>
<span class="fc" id="L232">    }).start();</span>
    
<span class="nc" id="L234">    verifier.waitForTest();</span>
<span class="nc" id="L235">  }</span>
  
  @Test (expected = RuntimeException.class)
  public void assertEqualsObjectFailAnotherThreadTest() throws InterruptedException, TimeoutException {
<span class="fc" id="L239">    new Thread(new Runnable() {</span>
      @Override
      public void run() {
        try {
<span class="nc" id="L243">          Thread.sleep(ASYNC_WAIT_AMOUNT);</span>
<span class="nc" id="L244">        } catch (InterruptedException e) {</span>
          // let thread exit
<span class="nc" id="L246">          return;</span>
<span class="nc" id="L247">        }</span>
        
<span class="nc" id="L249">        verifier.assertEquals(new Object(), new Object());</span>
<span class="nc" id="L250">      }</span>
<span class="fc" id="L251">    }).start();</span>
    
<span class="nc" id="L253">    verifier.waitForTest();</span>
<span class="nc" id="L254">  }</span>
  
  @Test (expected = RuntimeException.class)
  public void failTestAnotherThreadTest() throws InterruptedException, TimeoutException {
<span class="fc" id="L258">    new Thread(new Runnable() {</span>
      @Override
      public void run() {
        try {
<span class="nc" id="L262">          Thread.sleep(ASYNC_WAIT_AMOUNT);</span>
<span class="nc" id="L263">        } catch (InterruptedException e) {</span>
          // let thread exit
<span class="nc" id="L265">          return;</span>
<span class="nc" id="L266">        }</span>
        
<span class="nc" id="L268">        verifier.fail();</span>
<span class="nc" id="L269">      }</span>
<span class="fc" id="L270">    }).start();</span>
    
<span class="nc" id="L272">    verifier.waitForTest();</span>
<span class="nc" id="L273">  }</span>
  
  @Test (expected = RuntimeException.class)
  public void failMsgTestAnotherThreadTest() throws InterruptedException, TimeoutException {
<span class="fc" id="L277">    new Thread(new Runnable() {</span>
      @Override
      public void run() {
        try {
<span class="nc" id="L281">          Thread.sleep(ASYNC_WAIT_AMOUNT);</span>
<span class="nc" id="L282">        } catch (InterruptedException e) {</span>
          // let thread exit
<span class="nc" id="L284">          return;</span>
<span class="nc" id="L285">        }</span>
        
<span class="nc" id="L287">        verifier.fail(&quot;foo&quot;);</span>
<span class="nc" id="L288">      }</span>
<span class="fc" id="L289">    }).start();</span>
    
<span class="nc" id="L291">    verifier.waitForTest();</span>
<span class="nc" id="L292">  }</span>
  
  @Test (expected = RuntimeException.class)
  public void failThrowableTestAnotherThreadTest() throws InterruptedException, TimeoutException {
<span class="fc" id="L296">    new Thread(new Runnable() {</span>
      @Override
      public void run() {
        try {
<span class="nc" id="L300">          Thread.sleep(ASYNC_WAIT_AMOUNT);</span>
<span class="nc" id="L301">        } catch (InterruptedException e) {</span>
          // let thread exit
<span class="nc" id="L303">          return;</span>
<span class="nc" id="L304">        }</span>
        
<span class="nc" id="L306">        verifier.fail(new Exception());</span>
<span class="nc" id="L307">      }</span>
<span class="fc" id="L308">    }).start();</span>
    
<span class="nc" id="L310">    verifier.waitForTest();</span>
<span class="nc" id="L311">  }</span>
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.1.201803210924</span></div></body></html>