<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>SettableListenableFutureTest.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">threadly$All_in_threadly_test.exec</a> &gt; <a href="index.source.html" class="el_package">org.threadly.concurrent.future</a> &gt; <span class="el_source">SettableListenableFutureTest.java</span></div><h1>SettableListenableFutureTest.java</h1><pre class="source lang-java linenums">package org.threadly.concurrent.future;

import static org.junit.Assert.*;

import java.util.concurrent.CancellationException;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.threadly.BlockingTestRunnable;
import org.threadly.concurrent.PriorityScheduler;
import org.threadly.concurrent.StrictPriorityScheduler;
import org.threadly.test.concurrent.AsyncVerifier;
import org.threadly.test.concurrent.TestRunnable;
import org.threadly.util.Clock;
import org.threadly.util.StringUtils;

@SuppressWarnings(&quot;javadoc&quot;)
<span class="fc" id="L22">public class SettableListenableFutureTest extends ListenableFutureInterfaceTest {</span>
  protected SettableListenableFuture&lt;String&gt; slf;
  
  @Before
  public void setup() {
<span class="fc" id="L27">    slf = new SettableListenableFuture&lt;&gt;();</span>
<span class="fc" id="L28">  }</span>
  
  @After
  public void cleanup() {
<span class="fc" id="L32">    slf = null;</span>
<span class="fc" id="L33">  }</span>

  @Override
  protected ListenableFutureFactory makeListenableFutureFactory() {
<span class="fc" id="L37">    return new SettableListenableFutureFactory();</span>
  }
  
  @Test (expected = IllegalStateException.class)
  public void setResultResultFail() {
<span class="fc" id="L42">    slf.setResult(null);</span>
<span class="nc" id="L43">    slf.setResult(null);</span>
<span class="nc" id="L44">    fail(&quot;Should have thrown exception&quot;);</span>
<span class="nc" id="L45">  }</span>
  
  @Test
  public void setResultResultTest() {
<span class="fc" id="L49">    slf = new SettableListenableFuture&lt;&gt;(false);</span>
<span class="fc" id="L50">    assertTrue(slf.setResult(null));</span>
<span class="fc" id="L51">    assertFalse(slf.setResult(null));</span>
<span class="fc" id="L52">  }</span>
  
  @Test (expected = IllegalStateException.class)
  public void setFailureResultFail() {
<span class="fc" id="L56">    slf.setFailure(null);</span>
<span class="nc" id="L57">    slf.setResult(null);</span>
<span class="nc" id="L58">    fail(&quot;Should have thrown exception&quot;);</span>
<span class="nc" id="L59">  }</span>
  
  @Test
  public void setFailureResultTest() {
<span class="fc" id="L63">    slf = new SettableListenableFuture&lt;&gt;(false);</span>
<span class="fc" id="L64">    assertTrue(slf.setFailure(null));</span>
<span class="fc" id="L65">    assertFalse(slf.setResult(null));</span>
<span class="fc" id="L66">  }</span>
  
  @Test (expected = IllegalStateException.class)
  public void setResultFailureFail() {
<span class="fc" id="L70">    slf.setResult(null);</span>
<span class="nc" id="L71">    slf.setFailure(null);</span>
<span class="nc" id="L72">    fail(&quot;Should have thrown exception&quot;);</span>
<span class="nc" id="L73">  }</span>
  
  @Test
  public void setResultFailureTest() {
<span class="fc" id="L77">    slf = new SettableListenableFuture&lt;&gt;(false);</span>
<span class="fc" id="L78">    assertTrue(slf.setResult(null));</span>
<span class="fc" id="L79">    assertFalse(slf.setFailure(null));</span>
<span class="fc" id="L80">  }</span>
  
  @Test (expected = IllegalStateException.class)
  public void setFailureFailureFail() {
<span class="fc" id="L84">    slf.setFailure(null);</span>
<span class="nc" id="L85">    slf.setFailure(null);</span>
<span class="nc" id="L86">    fail(&quot;Should have thrown exception&quot;);</span>
<span class="nc" id="L87">  }</span>
  
  @Test
  public void setFailureFailureTest() {
<span class="fc" id="L91">    slf = new SettableListenableFuture&lt;&gt;(false);</span>
<span class="fc" id="L92">    assertTrue(slf.setFailure(null));</span>
<span class="fc" id="L93">    assertFalse(slf.setFailure(null));</span>
<span class="fc" id="L94">  }</span>
  
  @Test (expected = IllegalStateException.class)
  public void cancelSetResultFail() {
<span class="fc" id="L98">    slf.cancel(false);</span>
<span class="nc" id="L99">    slf.setResult(null);</span>
<span class="nc" id="L100">    fail(&quot;Should have thrown exception&quot;);</span>
<span class="nc" id="L101">  }</span>
  
  @Test
  public void cancelSetResultTest() {
<span class="fc" id="L105">    slf = new SettableListenableFuture&lt;&gt;(false);</span>
<span class="fc" id="L106">    assertTrue(slf.cancel(false));</span>
<span class="fc" id="L107">    assertFalse(slf.setResult(null));</span>
<span class="fc" id="L108">  }</span>
  
  @Test (expected = IllegalStateException.class)
  public void cancelSetFailureFail() {
<span class="fc" id="L112">    slf.cancel(false);</span>
<span class="nc" id="L113">    slf.setFailure(null);</span>
<span class="nc" id="L114">    fail(&quot;Should have thrown exception&quot;);</span>
<span class="nc" id="L115">  }</span>
  
  @Test
  public void cancelSetFailureTest() {
<span class="fc" id="L119">    slf = new SettableListenableFuture&lt;&gt;(false);</span>
<span class="fc" id="L120">    assertTrue(slf.cancel(false));</span>
<span class="fc" id="L121">    assertFalse(slf.setFailure(null));</span>
<span class="fc" id="L122">  }</span>
  
  @Test (expected = IllegalStateException.class)
  public void clearResultFail() {
<span class="nc" id="L126">    slf.clearResult();</span>
<span class="nc" id="L127">    fail(&quot;Should have thrown exception&quot;);</span>
<span class="nc" id="L128">  }</span>
  
  @Test (expected = IllegalStateException.class)
  public void getAfterClearResultFail() throws InterruptedException, ExecutionException {
<span class="fc" id="L132">    slf.setResult(null);</span>
<span class="fc" id="L133">    slf.clearResult();</span>
<span class="nc" id="L134">    slf.get();</span>
<span class="nc" id="L135">    fail(&quot;Should have thrown exception&quot;);</span>
<span class="nc" id="L136">  }</span>
  
  @Test (expected = IllegalStateException.class)
  public void getAfterClearFailureResultFail() throws InterruptedException, ExecutionException {
<span class="fc" id="L140">    slf.setFailure(null);</span>
<span class="fc" id="L141">    slf.clearResult();</span>
<span class="nc" id="L142">    slf.get();</span>
<span class="nc" id="L143">    fail(&quot;Should have thrown exception&quot;);</span>
<span class="nc" id="L144">  }</span>
  
  @Test
  public void listenersCalledOnResultTest() {
<span class="fc" id="L148">    listenersCalledTest(false);</span>
<span class="fc" id="L149">  }</span>
  
  @Test
  public void listenersCalledOnFailureTest() {
<span class="fc" id="L153">    listenersCalledTest(true);</span>
<span class="fc" id="L154">  }</span>
  
  public void listenersCalledTest(boolean failure) {
<span class="fc" id="L157">    TestRunnable tr = new TestRunnable();</span>
<span class="fc" id="L158">    slf.addListener(tr);</span>
    
<span class="fc bfc" id="L160" title="All 2 branches covered.">    if (failure) {</span>
<span class="fc" id="L161">      slf.setFailure(null);</span>
    } else {
<span class="fc" id="L163">      slf.setResult(null);</span>
    }
    
<span class="fc" id="L166">    assertTrue(tr.ranOnce());</span>
    
    // verify new additions also get called
<span class="fc" id="L169">    tr = new TestRunnable();</span>
<span class="fc" id="L170">    slf.addListener(tr);</span>
<span class="fc" id="L171">    assertTrue(tr.ranOnce());</span>
<span class="fc" id="L172">  }</span>
  
  @Test
  public void addCallbackTest() {
<span class="fc" id="L176">    String result = StringUtils.makeRandomString(5);</span>
<span class="fc" id="L177">    TestFutureCallback tfc = new TestFutureCallback();</span>
<span class="fc" id="L178">    slf.addCallback(tfc);</span>
    
<span class="fc" id="L180">    assertEquals(0, tfc.getCallCount());</span>
    
<span class="fc" id="L182">    slf.setResult(result);</span>
    
<span class="fc" id="L184">    assertEquals(1, tfc.getCallCount());</span>
<span class="pc bpc" id="L185" title="1 of 2 branches missed.">    assertTrue(result == tfc.getLastResult());</span>
<span class="fc" id="L186">  }</span>
  
  @Test
  public void addCallbackExecutionExceptionTest() {
<span class="fc" id="L190">    Throwable failure = new Exception();</span>
<span class="fc" id="L191">    TestFutureCallback tfc = new TestFutureCallback();</span>
<span class="fc" id="L192">    slf.addCallback(tfc);</span>
    
<span class="fc" id="L194">    assertEquals(0, tfc.getCallCount());</span>
    
<span class="fc" id="L196">    slf.setFailure(failure);</span>
    
<span class="fc" id="L198">    assertEquals(1, tfc.getCallCount());</span>
<span class="pc bpc" id="L199" title="1 of 2 branches missed.">    assertTrue(failure == tfc.getLastFailure());</span>
<span class="fc" id="L200">  }</span>
  
  @Test
  public void addAsCallbackResultTest() throws InterruptedException, ExecutionException {
<span class="fc" id="L204">    String testResult = StringUtils.makeRandomString(5);</span>
<span class="fc" id="L205">    ListenableFuture&lt;String&gt; resultFuture = new ImmediateResultListenableFuture&lt;&gt;(testResult);</span>
    
<span class="fc" id="L207">    resultFuture.addCallback(slf);</span>
    
<span class="fc" id="L209">    assertTrue(slf.isDone());</span>
<span class="fc" id="L210">    assertEquals(testResult, slf.get());</span>
<span class="fc" id="L211">  }</span>
  
  @Test
  public void addAsCallbackFailureTest() throws InterruptedException {
<span class="fc" id="L215">    Exception e = new Exception();</span>
<span class="fc" id="L216">    ListenableFuture&lt;String&gt; failureFuture = new ImmediateFailureListenableFuture&lt;&gt;(e);</span>
    
<span class="fc" id="L218">    failureFuture.addCallback(slf);</span>
    
<span class="fc" id="L220">    assertTrue(slf.isDone());</span>
    try {
<span class="nc" id="L222">      slf.get();</span>
<span class="nc" id="L223">      fail(&quot;Exception should have thrown&quot;);</span>
<span class="fc" id="L224">    } catch (ExecutionException ee) {</span>
<span class="pc bpc" id="L225" title="1 of 2 branches missed.">      assertTrue(ee.getCause() == e);</span>
<span class="nc" id="L226">    }</span>
<span class="fc" id="L227">  }</span>
  
  @Test
  public void cancelTest() {
<span class="fc" id="L231">    assertTrue(slf.cancel(false));</span>
<span class="fc" id="L232">    assertFalse(slf.cancel(false));</span>
    
<span class="fc" id="L234">    assertTrue(slf.isCancelled());</span>
<span class="fc" id="L235">    assertTrue(slf.isDone());</span>
<span class="fc" id="L236">  }</span>
  
  @Test
  public void cancelRunsListenersTest() {
<span class="fc" id="L240">    TestRunnable tr = new TestRunnable();</span>
<span class="fc" id="L241">    slf.addListener(tr);</span>
    
<span class="fc" id="L243">    slf.cancel(false);</span>
    
<span class="fc" id="L245">    assertTrue(tr.ranOnce());</span>
<span class="fc" id="L246">  }</span>
  
  @Test
  public void cancelWithInterruptTest() {
<span class="fc" id="L250">    BlockingTestRunnable btr = new BlockingTestRunnable();</span>
<span class="fc" id="L251">    Thread runningThread = new Thread(btr);</span>
    try {
<span class="fc" id="L253">      runningThread.start();</span>
<span class="fc" id="L254">      slf.setRunningThread(runningThread);</span>
<span class="fc" id="L255">      btr.blockTillStarted();</span>
      
<span class="fc" id="L257">      assertTrue(slf.cancel(true));</span>
      
      // should unblock when interrupted
<span class="fc" id="L260">      btr.blockTillFinished();</span>
    } finally {
<span class="fc" id="L262">      btr.unblock();</span>
    }
<span class="fc" id="L264">  }</span>
  
  @Test
  public void isDoneTest() {
<span class="fc" id="L268">    assertFalse(slf.isDone());</span>
    
<span class="fc" id="L270">    slf.setResult(null);</span>

<span class="fc" id="L272">    assertTrue(slf.isDone());</span>
<span class="fc" id="L273">  }</span>
  
  @Test
  public void getResultTest() throws InterruptedException, ExecutionException {
<span class="fc" id="L277">    final String testResult = StringUtils.makeRandomString(5);</span>
    
<span class="fc" id="L279">    PriorityScheduler scheduler = new StrictPriorityScheduler(1);</span>
    try {
<span class="fc" id="L281">      scheduler.schedule(new Runnable() {</span>
        @Override
        public void run() {
<span class="fc" id="L284">          slf.setResult(testResult);</span>
<span class="fc" id="L285">        }</span>
      }, DELAY_TIME);
      
<span class="pc bpc" id="L288" title="1 of 2 branches missed.">      assertTrue(slf.get() == testResult);</span>
    } finally {
<span class="fc" id="L290">      scheduler.shutdownNow();</span>
    }
<span class="fc" id="L292">  }</span>
  
  @Test
  public void getWithTimeoutResultTest() throws InterruptedException, 
                                                ExecutionException, 
                                                TimeoutException {
<span class="fc" id="L298">    final String testResult = StringUtils.makeRandomString(5);</span>
    
<span class="fc" id="L300">    PriorityScheduler scheduler = new StrictPriorityScheduler(1);</span>
    try {
<span class="fc" id="L302">      scheduler.prestartAllThreads();</span>
<span class="fc" id="L303">      scheduler.schedule(new Runnable() {</span>
        @Override
        public void run() {
<span class="fc" id="L306">          slf.setResult(testResult);</span>
<span class="fc" id="L307">        }</span>
      }, DELAY_TIME);
      
<span class="pc bpc" id="L310" title="2 of 4 branches missed.">      assertTrue(slf.get(DELAY_TIME + (SLOW_MACHINE ? 2000 : 1000), TimeUnit.MILLISECONDS) == testResult);</span>
    } finally {
<span class="fc" id="L312">      scheduler.shutdownNow();</span>
    }
<span class="fc" id="L314">  }</span>

  @Test
  public void getTimeoutTest() throws InterruptedException, 
                                      ExecutionException {
<span class="fc" id="L319">    long startTime = Clock.accurateForwardProgressingMillis();</span>
    try {
<span class="nc" id="L321">      slf.get(DELAY_TIME, TimeUnit.MILLISECONDS);</span>
<span class="nc" id="L322">      fail(&quot;Exception should have thrown&quot;);</span>
<span class="fc" id="L323">    } catch (TimeoutException e) {</span>
      // expected
<span class="nc" id="L325">    }</span>
<span class="fc" id="L326">    long endTime = Clock.accurateForwardProgressingMillis();</span>
    
<span class="pc bpc" id="L328" title="1 of 2 branches missed.">    assertTrue(endTime - startTime &gt;= DELAY_TIME);</span>
<span class="fc" id="L329">  }</span>
  
  @Test (expected = ExecutionException.class)
  public void getNullExceptionTest() throws InterruptedException, 
                                            ExecutionException {
<span class="fc" id="L334">    slf.setFailure(null);</span>
<span class="nc" id="L335">    slf.get();</span>
<span class="nc" id="L336">  }</span>
  
  @Test
  public void getExecutionExceptionTest() throws InterruptedException {
<span class="fc" id="L340">    Exception failure = new Exception();</span>
<span class="fc" id="L341">    slf.setFailure(failure);</span>
    
    try {
<span class="nc" id="L344">      slf.get();</span>
<span class="nc" id="L345">      fail(&quot;Exception should have thrown&quot;);</span>
<span class="fc" id="L346">    } catch (ExecutionException e) {</span>
<span class="pc bpc" id="L347" title="1 of 2 branches missed.">      assertTrue(failure == e.getCause());</span>
<span class="nc" id="L348">    }</span>
<span class="fc" id="L349">  }</span>
  
  @Test
  public void getWithTimeoutExecutionExceptionTest() throws InterruptedException, 
                                                            TimeoutException {
<span class="fc" id="L354">    Exception failure = new Exception();</span>
<span class="fc" id="L355">    slf.setFailure(failure);</span>
    
    try {
<span class="nc" id="L358">      slf.get(100, TimeUnit.MILLISECONDS);</span>
<span class="nc" id="L359">      fail(&quot;Exception should have thrown&quot;);</span>
<span class="fc" id="L360">    } catch (ExecutionException e) {</span>
<span class="pc bpc" id="L361" title="1 of 2 branches missed.">      assertTrue(failure == e.getCause());</span>
<span class="nc" id="L362">    }</span>
<span class="fc" id="L363">  }</span>
  
  @Test
  public void getCancellationTest() throws InterruptedException, ExecutionException {
<span class="fc" id="L367">    slf.cancel(false);</span>
    
    try {
<span class="nc" id="L370">      slf.get();</span>
<span class="nc" id="L371">      fail(&quot;Exception should have thrown&quot;);</span>
<span class="fc" id="L372">    } catch (CancellationException e) {</span>
      // expected
<span class="nc" id="L374">    }</span>
<span class="fc" id="L375">  }</span>
  
  @Test
  public void getWithTimeoutCancellationTest() throws InterruptedException, ExecutionException, TimeoutException {
<span class="fc" id="L379">    slf.cancel(false);</span>
    
    try {
<span class="nc" id="L382">      slf.get(100, TimeUnit.MILLISECONDS);</span>
<span class="nc" id="L383">      fail(&quot;Exception should have thrown&quot;);</span>
<span class="fc" id="L384">    } catch (CancellationException e) {</span>
      // expected
<span class="nc" id="L386">    }</span>
<span class="fc" id="L387">  }</span>
  
  @Test
  public void chainCanceledFutureTest() {
<span class="fc" id="L391">    SettableListenableFuture&lt;String&gt; canceledSlf = new SettableListenableFuture&lt;&gt;();</span>
<span class="fc" id="L392">    assertTrue(canceledSlf.cancel(false));</span>
    
<span class="fc" id="L394">    canceledSlf.addCallback(slf);</span>
    
<span class="fc" id="L396">    assertTrue(slf.isCancelled());</span>
<span class="fc" id="L397">  }</span>
  
  @Test
  public void cancelChainedFutureTest() {
<span class="fc" id="L401">    SettableListenableFuture&lt;String&gt; canceledSlf = new SettableListenableFuture&lt;&gt;();</span>
    
<span class="fc" id="L403">    canceledSlf.addCallback(slf);</span>
<span class="fc" id="L404">    assertTrue(canceledSlf.cancel(false));</span>
    
<span class="fc" id="L406">    assertTrue(slf.isCancelled());</span>
<span class="fc" id="L407">  }</span>
  
  @Test
  public void cancelFlatMappedAsyncFutureTest() {
<span class="fc" id="L411">    SettableListenableFuture&lt;Void&gt; asyncSLF = new SettableListenableFuture&lt;&gt;();</span>
<span class="fc" id="L412">    ListenableFuture&lt;Void&gt; mappedLF = slf.flatMap(asyncSLF);</span>
      
<span class="fc" id="L414">    slf.setResult(null);  // complete source future before cancel</span>
<span class="fc" id="L415">    assertFalse(mappedLF.isDone());</span>
<span class="fc" id="L416">    assertTrue(mappedLF.cancel(false)); // no interrupt needed, delegate future not started</span>
<span class="fc" id="L417">    assertTrue(asyncSLF.isCancelled());</span>
<span class="fc" id="L418">  }</span>
  
  private static void verifyCancelationExceptionMessageOnGet(String msg, ListenableFuture&lt;?&gt; lf) throws InterruptedException {
    try {
<span class="nc" id="L422">      lf.get();</span>
<span class="nc" id="L423">      fail(&quot;Exception should have thrown&quot;);</span>
<span class="fc" id="L424">    } catch (ExecutionException e) {</span>
<span class="fc" id="L425">      assertEquals(msg, e.getCause().getMessage());</span>
<span class="fc" id="L426">    } catch (CancellationException e) {</span>
<span class="fc" id="L427">      assertEquals(msg, e.getMessage());</span>
<span class="pc" id="L428">    }</span>
<span class="fc" id="L429">  }</span>
  
  private static void verifyCancelationExceptionMessageInCallback(String msg, ListenableFuture&lt;?&gt; lf) throws InterruptedException, TimeoutException {
<span class="fc" id="L432">    AsyncVerifier av = new AsyncVerifier();</span>
<span class="fc" id="L433">    lf.addCallback(new FutureCallback&lt;Object&gt;() {</span>
      @Override
      public void handleResult(Object result) {
<span class="nc" id="L436">        av.fail();</span>
<span class="nc" id="L437">      }</span>

      @Override
      public void handleFailure(Throwable t) {
<span class="fc" id="L441">        av.assertEquals(msg, t.getMessage());</span>
<span class="fc" id="L442">        av.signalComplete();</span>
<span class="fc" id="L443">      }</span>
    });
<span class="fc" id="L445">    av.waitForTest();</span>
<span class="fc" id="L446">  }</span>
  
  @Test
  public void cancelationExceptionMessageTest() throws InterruptedException {
<span class="fc" id="L450">    String msg = StringUtils.makeRandomString(5);</span>
<span class="fc" id="L451">    SettableListenableFuture&lt;Void&gt; slf = new CancelMessageTestSettableListenableFuture(msg);</span>
<span class="fc" id="L452">    slf.cancel(false);</span>
    
<span class="fc" id="L454">    verifyCancelationExceptionMessageOnGet(msg, slf);</span>
<span class="fc" id="L455">  }</span>
  
  @Test
  public void futureCallbackCancelationExceptionMessageTest() throws InterruptedException, TimeoutException {
<span class="fc" id="L459">    String msg = StringUtils.makeRandomString(5);</span>
<span class="fc" id="L460">    SettableListenableFuture&lt;Void&gt; slf = new CancelMessageTestSettableListenableFuture(msg);</span>
<span class="fc" id="L461">    slf.cancel(false);</span>
    
<span class="fc" id="L463">    verifyCancelationExceptionMessageInCallback(msg, slf);</span>
<span class="fc" id="L464">  }</span>
  
  @Test
  public void mapCancelationExceptionMessageAlreadyDoneTest() throws InterruptedException, TimeoutException {
<span class="fc" id="L468">    String msg = StringUtils.makeRandomString(5);</span>
<span class="fc" id="L469">    SettableListenableFuture&lt;Void&gt; slf = new CancelMessageTestSettableListenableFuture(msg);</span>
<span class="fc" id="L470">    slf.cancel(false);</span>
<span class="pc" id="L471">    ListenableFuture&lt;Void&gt; mappedFuture = slf.map((v) -&gt; v);</span>

<span class="fc" id="L473">    verifyCancelationExceptionMessageOnGet(msg, mappedFuture);</span>
<span class="fc" id="L474">    verifyCancelationExceptionMessageInCallback(msg, mappedFuture);</span>
<span class="fc" id="L475">  }</span>
  
  @Test
  public void mapCancelationExceptionMessageTest() throws InterruptedException, TimeoutException {
<span class="fc" id="L479">    String msg = StringUtils.makeRandomString(5);</span>
<span class="fc" id="L480">    SettableListenableFuture&lt;Void&gt; slf = new CancelMessageTestSettableListenableFuture(msg);</span>
<span class="pc" id="L481">    ListenableFuture&lt;Void&gt; mappedFuture = slf.map((v) -&gt; v);</span>
<span class="fc" id="L482">    slf.cancel(false);</span>

<span class="fc" id="L484">    verifyCancelationExceptionMessageOnGet(msg, mappedFuture);</span>
<span class="fc" id="L485">    verifyCancelationExceptionMessageInCallback(msg, mappedFuture);</span>
<span class="fc" id="L486">  }</span>
  
  @Test
  public void flatMapCancelationExceptionMessageAlreadyDoneTest() throws InterruptedException, TimeoutException {
<span class="fc" id="L490">    String msg = StringUtils.makeRandomString(5);</span>
<span class="fc" id="L491">    SettableListenableFuture&lt;Void&gt; slf = new CancelMessageTestSettableListenableFuture(msg);</span>
<span class="fc" id="L492">    slf.cancel(false);</span>
<span class="pc" id="L493">    ListenableFuture&lt;Void&gt; mappedFuture = slf.flatMap((v) -&gt; FutureUtils.immediateResultFuture(null));</span>

<span class="fc" id="L495">    verifyCancelationExceptionMessageOnGet(msg, mappedFuture);</span>
<span class="fc" id="L496">    verifyCancelationExceptionMessageInCallback(msg, mappedFuture);</span>
<span class="fc" id="L497">  }</span>
  
  @Test
  public void flatMapCancelationExceptionMessageTest() throws InterruptedException, TimeoutException {
<span class="fc" id="L501">    String msg = StringUtils.makeRandomString(5);</span>
<span class="fc" id="L502">    SettableListenableFuture&lt;Void&gt; slf = new CancelMessageTestSettableListenableFuture(msg);</span>
<span class="pc" id="L503">    ListenableFuture&lt;Void&gt; mappedFuture = slf.flatMap((v) -&gt; FutureUtils.immediateResultFuture(null));</span>
<span class="fc" id="L504">    slf.cancel(false);</span>

<span class="fc" id="L506">    verifyCancelationExceptionMessageOnGet(msg, mappedFuture);</span>
<span class="fc" id="L507">    verifyCancelationExceptionMessageInCallback(msg, mappedFuture);</span>
<span class="fc" id="L508">  }</span>
  
  @Test
  public void failureMapCancelationExceptionMessageAlreadyDoneTest() throws InterruptedException, TimeoutException {
<span class="fc" id="L512">    String msg = StringUtils.makeRandomString(5);</span>
<span class="fc" id="L513">    SettableListenableFuture&lt;Void&gt; slf = new CancelMessageTestSettableListenableFuture(msg);</span>
<span class="fc" id="L514">    slf.cancel(false);</span>
<span class="fc" id="L515">    ListenableFuture&lt;Void&gt; mappedFuture = slf.mapFailure(CancellationException.class, </span>
                                                         (c) -&gt; { 
<span class="fc" id="L517">                                                           throw c;</span>
                                                         });

<span class="fc" id="L520">    verifyCancelationExceptionMessageOnGet(msg, mappedFuture);</span>
<span class="fc" id="L521">    verifyCancelationExceptionMessageInCallback(msg, mappedFuture);</span>
<span class="fc" id="L522">  }</span>
  
  @Test
  public void failureMapCancelationExceptionMessageTest() throws InterruptedException, TimeoutException {
<span class="fc" id="L526">    String msg = StringUtils.makeRandomString(5);</span>
<span class="fc" id="L527">    SettableListenableFuture&lt;Void&gt; slf = new CancelMessageTestSettableListenableFuture(msg);</span>
<span class="fc" id="L528">    ListenableFuture&lt;Void&gt; mappedFuture = slf.mapFailure(CancellationException.class, </span>
                                                         (c) -&gt; { 
<span class="fc" id="L530">                                                           throw c;</span>
                                                         });
<span class="fc" id="L532">    slf.cancel(false);</span>

<span class="fc" id="L534">    verifyCancelationExceptionMessageOnGet(msg, mappedFuture);</span>
<span class="fc" id="L535">    verifyCancelationExceptionMessageInCallback(msg, mappedFuture);</span>
<span class="fc" id="L536">  }</span>
  
  @Test
  public void failureFlatMapCancelationExceptionMessageAlreadyDoneTest() throws InterruptedException, TimeoutException {
<span class="fc" id="L540">    String msg = StringUtils.makeRandomString(5);</span>
<span class="fc" id="L541">    SettableListenableFuture&lt;Void&gt; slf = new CancelMessageTestSettableListenableFuture(msg);</span>
<span class="fc" id="L542">    slf.cancel(false);</span>
<span class="fc" id="L543">    ListenableFuture&lt;Void&gt; mappedFuture = slf.flatMapFailure(CancellationException.class, </span>
<span class="fc" id="L544">                                                             (c) -&gt; FutureUtils.immediateFailureFuture(c));</span>

<span class="fc" id="L546">    verifyCancelationExceptionMessageOnGet(msg, mappedFuture);</span>
<span class="fc" id="L547">    verifyCancelationExceptionMessageInCallback(msg, mappedFuture);</span>
<span class="fc" id="L548">  }</span>
  
  @Test
  public void failureFlatMapCancelationExceptionMessageTest() throws InterruptedException, TimeoutException {
<span class="fc" id="L552">    String msg = StringUtils.makeRandomString(5);</span>
<span class="fc" id="L553">    SettableListenableFuture&lt;Void&gt; slf = new CancelMessageTestSettableListenableFuture(msg);</span>
<span class="fc" id="L554">    ListenableFuture&lt;Void&gt; mappedFuture = slf.flatMapFailure(CancellationException.class, </span>
<span class="fc" id="L555">                                                             (c) -&gt; FutureUtils.immediateFailureFuture(c));</span>
<span class="fc" id="L556">    slf.cancel(false);</span>

<span class="fc" id="L558">    verifyCancelationExceptionMessageOnGet(msg, mappedFuture);</span>
<span class="fc" id="L559">    verifyCancelationExceptionMessageInCallback(msg, mappedFuture);</span>
<span class="fc" id="L560">  }</span>
  
  @Test
  public void getRunningStackTraceTest() {
<span class="fc" id="L564">    assertNull(slf.getRunningStackTrace());</span>
    
<span class="fc" id="L566">    slf.setRunningThread(Thread.currentThread());</span>
<span class="fc" id="L567">    StackTraceElement[] stack = slf.getRunningStackTrace();</span>
<span class="fc" id="L568">    assertEquals(this.getClass().getName(), stack[2].getClassName());</span>

<span class="fc" id="L570">    slf.setResult(null);</span>
<span class="fc" id="L571">    assertNull(slf.getRunningStackTrace());</span>
<span class="fc" id="L572">  }</span>
  
  @Test
  public void getMappedRunningStackTraceTest() {
<span class="fc" id="L576">    ListenableFuture&lt;Object&gt; mappedFuture = slf.map((o) -&gt; o).map((o) -&gt; null);</span>
    
<span class="fc" id="L578">    assertNull(mappedFuture.getRunningStackTrace());</span>
    
<span class="fc" id="L580">    slf.setRunningThread(Thread.currentThread());</span>
<span class="fc" id="L581">    StackTraceElement[] stack = mappedFuture.getRunningStackTrace();</span>
<span class="fc" id="L582">    assertEquals(this.getClass().getName(), stack[4].getClassName());</span>

<span class="fc" id="L584">    slf.setResult(null);</span>
<span class="fc" id="L585">    assertNull(mappedFuture.getRunningStackTrace());</span>
<span class="fc" id="L586">  }</span>
  
  @Test
  public void getFlatMappedRunningStackTraceTest() {
<span class="fc" id="L590">    ListenableFuture&lt;Object&gt; mappedFuture = </span>
<span class="fc" id="L591">        slf.flatMap((o) -&gt; FutureUtils.immediateResultFuture(o))</span>
<span class="fc" id="L592">           .flatMap((o) -&gt; FutureUtils.immediateResultFuture(null));</span>
    
<span class="fc" id="L594">    assertNull(mappedFuture.getRunningStackTrace());</span>
    
<span class="fc" id="L596">    slf.setRunningThread(Thread.currentThread());</span>
<span class="fc" id="L597">    StackTraceElement[] stack = mappedFuture.getRunningStackTrace();</span>
<span class="fc" id="L598">    assertEquals(this.getClass().getName(), stack[4].getClassName());</span>

<span class="fc" id="L600">    slf.setResult(null);</span>
<span class="fc" id="L601">    assertNull(mappedFuture.getRunningStackTrace());</span>
<span class="fc" id="L602">  }</span>
  
  private static class SettableListenableFutureFactory implements ListenableFutureFactory {
    @Override
    public ListenableFuture&lt;?&gt; makeCanceled() {
<span class="fc" id="L607">      SettableListenableFuture&lt;?&gt; slf = new SettableListenableFuture&lt;&gt;();</span>
<span class="fc" id="L608">      slf.cancel(false);</span>
<span class="fc" id="L609">      return slf;</span>
    }
    
    @Override
    public ListenableFuture&lt;Object&gt; makeWithFailure(Exception e) {
<span class="fc" id="L614">      SettableListenableFuture&lt;Object&gt; slf = new SettableListenableFuture&lt;&gt;();</span>
<span class="fc" id="L615">      slf.handleFailure(e);</span>
<span class="fc" id="L616">      return slf;</span>
    }

    @Override
    public &lt;T&gt; ListenableFuture&lt;T&gt; makeWithResult(T result) {
<span class="fc" id="L621">      SettableListenableFuture&lt;T&gt; slf = new SettableListenableFuture&lt;&gt;();</span>
<span class="fc" id="L622">      slf.handleResult(result);</span>
<span class="fc" id="L623">      return slf;</span>
    }
  }
  
  private static class CancelMessageTestSettableListenableFuture extends SettableListenableFuture&lt;Void&gt; {
    private final String msg;
    
<span class="fc" id="L630">    public CancelMessageTestSettableListenableFuture(String msg) {</span>
<span class="fc" id="L631">      this.msg = msg;</span>
<span class="fc" id="L632">    }</span>
    
    @Override
    protected String getCancellationExceptionMessage() {
<span class="fc" id="L636">      return msg;</span>
    }
  }
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.1.201803210924</span></div></body></html>